### ISSUE TITLE
Two large tests for 365 days. 

### ISSUE THREAD

**Issue by lunamonkey** [bancacy/BNY-Smart-Contract#3]
https://github.com/bancacy/BNY-Smart-Contract/blob/37868590d905d16503dfddf9fd43b3f85e202eb5/contracts/BNY.sol#L266

The test for 365 happens twice, one the second test transfers are being carried out also. Why twice?

**Comment by AndyPuppyZ** [comment]
The second 'if' is inside the 'while' loop, in case the investor didnt claim it after 365, it will loop inside the while loop and stop when the day is 365.
